### ISSUE TITLE
[Question] configure puma to use unix?

### ISSUE THREAD

**Issue by alexcp91** [mattbrictson/tomo#143]
First of, thank you for this wonderful tool. It has drastically simplified configuration and deployment. The readme states that "The tomo puma plugin assumes that your puma server will listen on a single TCP port for HTTP (not HTTPS) traffic." I'm having difficulty configuring nginx with puma using TCP. How would I go about changing to UNIX? Is this doable?

**Comment by mattbrictson** [comment]
Hi @alexcp91 great to hear that you are having a good experience with tomo! Thanks for the question.

I have a couple projects that are using tomo for deployment and have ngnix configured to talk to puma using TCP. I have used UNIX sockets in the past but I prefer TCP these days because it is easy to troubleshoot. Using TCP is a good default because it means that even if someone is not using nginx, they can still deploy an app using tomo with clients connecting directly to puma over TCP. Or you can put a load balancer or cloud reverse proxy in front of puma over TCP as well. UNIX sockets on the other hand are more limited.

That is all to say that I don't have plans to support puma UNIX sockets with tomo. If you were to go with that option I think you'd have to implement your own custom tomo tasks. It is certainly possible but not a trivial amount of work.

I would love to help you get nginx+puma over TCP working because I think that is an easier solution. I can start by sharing the nginx config that I am using in my projects. Would that help? What error are you seeing?

**Comment by mattbrictson** [comment]
Actually, there might be a way to make puma work with UNIX sockets just by updating the systemd templates that tomo uses. The templates the ship out of the box assume TCP, but you can provide your own.

For example, you could update your tomo config as follows:

```ruby
set puma_systemd_service_template_path: "./templates/puma_service.erb"
set puma_systemd_socket_template_path: "./templates/puma_socket.erb"
```

And also remove the `puma:check_active` task from the `deploy` config, since this assumes a TCP connection.

Then, create the two custom template files (referenced in the settings above):

```
.tomo/templates/puma_service.erb
.tomo/templates/puma_socket.erb
```

With the following contents:

<details>

```
# puma_service.erb
[Unit]
Description=Puma HTTP Server for <%= settings[:application] %>
After=network.target
Requires=<%= settings[:puma_systemd_socket] %>
ConditionPathExists=<%= paths.current %>

[Service]
ExecStart=/bin/bash -lc 'exec bundle exec --keep-file-descriptors puma -C config/puma.rb -b unix://<%= paths.shared.join("tmp/sockets/puma.sock") %>'
KillMode=mixed
Restart=always
StandardError=syslog
StandardInput=null
StandardOutput=syslog
SyslogIdentifier=%n
TimeoutStopSec=5
Type=simple
WorkingDirectory=<%= paths.current %>
# Helpful for debugging socket activation, etc.
# Environment=PUMA_DEBUG=1

[Install]
WantedBy=default.target
```

```
# puma_socket.erb
[Unit]
Description=Puma HTTP Server Accept Sockets for <%= settings[:application] %>

[Socket]
ListenStream=<%= paths.shared.join("tmp/sockets/puma.sock") %>

# Socket options matching Puma defaults
NoDelay=true
ReusePort=true
Backlog=1024

[Install]
WantedBy=sockets.target
```

Notice how I have specified the UNIX socket path for `ListenStream` and the `-b` option in the puma command. These need to match.

</details>

Then rerun `tomo setup` to reinstall the systemd config.

I haven't tried this myself, but hopefully this sets you in the right direction. You can also refer to the official puma guide here: https://github.com/puma/puma/blob/master/docs/systemd.md#socket-activation

**Comment by alexcp91** [comment]
Matt,

Thank you for this. This is super helpful. I was able to get it working via nginx & TCP as soon as I figured I wasn't properly setting my APPLICATION_HOST ENV variable in production. Thanks again for all your help!

**Comment by mattbrictson** [comment]
Great to hear you got it working! I'll close the issue.

**Comment by mhassaan** [comment]
hi @mattbrictson i know this issue is closed but i have stumbled upon this discussion looking for the solution to configure nginx with puma on unix sockets but no luck so far. Here is the sample configuration i am using 

Configuration for puma
```
# Set up socket location
bind "unix:///var/www/my_app/shared/sockets/puma.sock"
```

Configuration for nginx, 
```
upstream app {
     server unix:/var/www/my_app/shared/sockets/puma.sock fail_timeout=0;
}
```
but all i get in the logs is `Permission denied while connecting to upstream`. Since tomo binds puma on tcp socket when `puma:restart` is executed. Any idea how to make it work with tcp? Thanks

**Comment by mattbrictson** [comment]
My experience is with tcp-based upstream, which is what tomo does by default. I am not sure how to troubleshoot the `unix:` based upstream. Based on the error message, I would guess it is a file permission issue? Do the deployer user and the nginx user both have access to `/var/www/my_app/shared/sockets/puma.sock`?

These discussions might help:

https://github.com/puma/puma/issues/44#issuecomment-4848342
https://stackoverflow.com/questions/21820444/nginx-error-13-permission-denied-while-connecting-to-upstream

**Comment by mattbrictson** [comment]
You may also need to add a `umask` parameter to your `bind` directive in your puma config:

https://github.com/puma/puma/blob/master/README.md#binding-tcp--sockets

**Comment by mhassaan** [comment]
@mattbrictson thanks a lot for suggestions, it works now. However, how to make it possible on tcp connections with nginx? Can you share your nginx configurations?

**Comment by mattbrictson** [comment]
@mhassaan does this help? https://github.com/mattbrictson/tomo/issues/78#issuecomment-555121565

**Comment by mhassaan** [comment]
@mattbrictson surely it does. Thanks a lot for detailed info.
