### ISSUE TITLE
Take rbenv_ruby_version from .ruby-version file by default

### ISSUE THREAD

**Issue by uxxman** [mattbrictson/tomo#186]
It is a common convention in rbenv (even rvm) projects to define **.ruby-version** file for the project to automatically switch to the right ruby version. Rails projects also generates this file for you by default. So, instead of setting this value at 2 different places and risking them to get out of sync during an upgrade, can we make the default value of **rbenv_ruby_version** to consider .ruby-version file if it exists? For example

https://github.com/mattbrictson/tomo/blob/4734946f235af330902e85b0d4cf17d15ebdf1b1/lib/tomo/plugin/rbenv.rb#L8

with

```ruby
rbenv_ruby_version: File.exist?(".ruby-version") ? File.read(".ruby-version").strip : nil
```

**Comment by mattbrictson** [comment]
I think this could work. In fact, tomo does something similar for bundler where if `bundler_version` is `nil`, it will read the bundler version from the `Gemfile.lock`:

https://github.com/mattbrictson/tomo/blob/4734946f235af330902e85b0d4cf17d15ebdf1b1/lib/tomo/plugin/bundler/tasks.rb#L32

Generally speaking I try to avoid that kind of magic, though. Different deployment tools use different files. Heroku, for example, [looks for a `ruby` declaration inside the `Gemfile`](https://devcenter.heroku.com/articles/ruby-versions#selecting-a-version-of-ruby) and does not use `.ruby-version`. So that inconsistent magic might confuse people.

But, considering that `rails new` generates a `.ruby-version` by default, this does seem reasonable. So I am willing to try it.

I guess that means that going forward, `tomo init` would no longer automatically put the Ruby version in the `.tomo/config.yml` file for you? In other words, we'd remove this line:

https://github.com/mattbrictson/tomo/blob/4734946f235af330902e85b0d4cf17d15ebdf1b1/lib/tomo/templates/config.rb.erb#L17

In terms of reading the `.ruby-version` file, I think that needs to be done server-side. Because you want the version of Ruby installed to match the code that is being deployed, not what you have locally. In some cases they might be different; e.g. if you have the `develop` branch checked out locally but you are asking tomo to deploy `main`.

So something like the bundler plugin does server-side:

https://github.com/mattbrictson/tomo/blob/4734946f235af330902e85b0d4cf17d15ebdf1b1/lib/tomo/plugin/bundler/tasks.rb#L53-L65

Does that sound right?

If you want to put together a PR, feel free to give it a shot. I'd appreciate more contributors. 🙂

**Comment by uxxman** [comment]
> I guess that means that going forward, `tomo init` would no longer automatically put the Ruby version in the `.tomo/config.yml` file for you? In other words, we'd remove this line:

Exactly 👍 One less config to worry about 😉 



> In terms of reading the `.ruby-version` file, I think that needs to be done server-side. Because you want the version of Ruby installed to match the code that is being deployed, not what you have locally. In some cases they might be different; e.g. if you have the `develop` branch checked out locally but you are asking tomo to deploy `main`.

Again agreed 👍 They can surely differ in some scenarios and the server side value is important, not the local one.



> If you want to put together a PR, feel free to give it a shot. I'd appreciate more contributors. 🙂

Sure, would love to ❤️ I will checkout the code in bundler plugin and try to put together a PR using something similar for rbenv ruby version config 👍

**Comment by uxxman** [comment]
Thanks for the merge 👍 😄 closing the issue
