### ISSUE TITLE
host member variable not accessible to custom tasks through API

### ISSUE THREAD

**Issue by Fredlander** [mattbrictson/tomo#434]
Tomo looks good and I'm trying to replace Capistrano with it. One issue that bugs me is that when I create a custom task I can't access the Host api directly, like I can with Paths, Logger, etc.

so this task fails because of undefined variable host (paths works fine)

```
def test
  puts host.user, paths.current
end
```

to make it work I have to define host explicitly :

```
def test
  host = Runtime::Current.host
  puts host.user, paths.current
end

```
This is not mentioned in the docs. The only reason I know this because I read through the code. Can this be fixed please?

**Comment by mattbrictson** [comment]
Hi @Fredlander , sorry I missed this issue. The way I recommend accessing the host in a task would be

```ruby
def test
  puts remote.host, paths.current
end
```

This is by design, because `host` by itself is ambiguous (it could refer to the local host). Accessing it through `remote` makes it more explicit.

I agree this could be better documented. Would it make sense to put it here? https://tomo.mattbrictson.com/api/TaskLibrary/#remote-tomoremote

**Comment by Fredlander** [comment]
Hey @mattbrictson, thanks for the response. What you say makes sense, this is indeed mentioned under https://tomo.mattbrictson.com/api/Remote/ but I missed it as I was looking at TaskLibrary documentation. I think It would be harder to miss if this was also stated under https://tomo.mattbrictson.com/api/TaskLibrary/#remote-tomoremote but it's no biggie now I know what's going on :)

Thanks again!
