### ISSUE TITLE
[QUESTION] Is there anything specific to configure for Nginx?

### ISSUE THREAD

**Issue by designium** [mattbrictson/tomo#78]
Hi,

Just a quick question about Nginx, I just configure the pointer from Nginx to the:

    set deploy_to: "/var/www/%{application}" 

Right?

Also, I can setup multiple rails app into the same machine using the same logic? Thanks

**Comment by mattbrictson** [comment]
If you've already installed nginx using `apt-get install nginx`, then setting it up for your Rails app involves creating an appropriate config file in `/etc/nginx/sites-enabled/` and then restarting nginx. Here is a basic config that should work for Rails. The important parts are the puma port number (3000) and the path to your Rails public directory (`/var/www/my-app/current/public`):

```nginx
upstream rails-puma {
  server 127.0.0.1:3000 fail_timeout=0;
}

server {
  listen 80 deferred;
  server_name example.com;
  server_name www.example.com;
  client_max_body_size 4G;
  root /var/www/my-app/current/public;

  try_files $uri/index.html $uri @puma;
  location @puma {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://rails-puma;
  }

  error_page 500 502 503 504 /500.html;
  location = /500.html {
    root /var/www/my-app/current/public;
  }
}
```

> Also, I can setup multiple rails app into the same machine using the same logic?

I have not tried this myself, and it is not a scenario that I am intentionally building tomo to support, but it should work. It is important that you create a separate deploy user for each app. That way each can have its own environment variables. You'll also need to set a different `:puma_port` for each app so that they don't collide.

**Comment by designium** [comment]
Thanks!!!!
